### ISSUE TITLE
Error running Example

### ISSUE THREAD

**Issue by enzyme69** [fogleman/sdf#10]
$ python examples/example.py
```
Traceback (most recent call last):
  File "examples/example.py", line 1, in <module>
    from sdf import *
  File "/Users/jimmygunawan/sdf/sdf/__init__.py", line 1, in <module>
    from . import d2, d3, ease
  File "/Users/jimmygunawan/sdf/sdf/d2.py", line 5, in <module>
    from . import dn, d3, ease
  File "/Users/jimmygunawan/sdf/sdf/dn.py", line 7
    def union(a, *bs, k=None):
                      ^
SyntaxError: invalid syntax
```

**Comment by enzyme69** [comment]
Hmm ok python3 examples/example.py seems to work

<img width="803" alt="Screen Shot 2021-02-21 at 9 23 40 pm" src="https://user-images.githubusercontent.com/3952687/108622173-12d29980-748b-11eb-914a-83c647752fd9.png">

**Comment by sixclones** [comment]
For the records, I faced the same problem but just running `python3 examples/example.py` wasn't enough.
I needed to run `pip3 install -e .` (instead of `pip install -e .`).
