### ISSUE TITLE
Running pawn example fails

### ISSUE THREAD

**Issue by rdvdijk** [fogleman/sdf#14]
Running the `pawn.py` example fails. I followed the steps in the `README` and used `virtualenv` and `pip` as suggested.

All other examples work for me.

```sh
$ python examples/pawn.py
Traceback (most recent call last):
  File "examples/pawn.py", line 8, in <module>
    f = section(0, 0.2, 1, 1.25)
  File "examples/pawn.py", line 4, in section
    f = cylinder(d0/2).transition(
  File "...../sdf/sdf/d3.py", line 30, in __getattr__
    raise AttributeError
AttributeError
```

Any idea what causes this?

**Comment by fogleman** [comment]
Fixed, due to a renamed function
