### ISSUE TITLE
RecursionError for large number of objects

### ISSUE THREAD

**Issue by hweom** [fogleman/sdf#43]
```python
import random
from sdf import *

part = box(1)
for i in range(0, 100):
    for j in range(0, 100):
        part |= box((10, 10, 2)).translate((i * 5, j * 5, random.uniform(0, 0.5)))

part.save('part.stl', samples=2**20)
```

results in 
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    part.save('part.stl', samples=2**20)
  File "/usr/lib/python3.11/site-packages/sdf/d3.py", line 43, in save
    return mesh.save(path, self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sdf/mesh.py", line 152, in save
    points = generate(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sdf/mesh.py", line 92, in generate
    bounds = _estimate_bounds(sdf)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sdf/mesh.py", line 77, in _estimate_bounds
    volume = sdf(P).reshape((len(X), len(Y), len(Z)))
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/sdf/d3.py", line 25, in __call__
    return self.f(p).reshape((-1, 1))
...
  File "/usr/lib/python3.11/site-packages/sdf/d3.py", line 25, in __call__
    return self.f(p).reshape((-1, 1))
           ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sdf/dn.py", line 9, in f
    d1 = a(p)
         ^^^^
  File "/usr/lib/python3.11/site-packages/sdf/d3.py", line 25, in __call__
    return self.f(p).reshape((-1, 1))
           ^^^^^^^^^
```

**Comment by nobodyinperson** [comment]
Duplicate of #23 and #40. Solution is [here](https://github.com/fogleman/sdf/issues/40#issuecomment-1667559330), which is to use `union(...)` instead of the `|=` operator.

**Comment by hweom** [comment]
Ah, thanks.
